import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useReducer, useCallback } from 'react';
import Select, { ActionMeta, Props as SelectProps } from 'react-select'

const states = [
  { value: 0, label: 'Texas' },
  { value: 1, label: 'Louisiana' }
]

const allMetros = [
  [
    { value: 0, label: "Dallas" },
    { value: 1, label: "Houston" }
  ],
  [
    { value: 0, label: "Bossier" },
    { value: 1, label: "Haughton" }
  ]
]

const StateSelect = (props: SelectProps) => (
  <Select {...props} isClearable />
)

const MetroSelect = (props: SelectProps) => (
  <Select {...props} isMulti isClearable isDisabled={!props.options?.length} />
)

interface Option
{
  value: number,
  label: string
}

interface FilterState
{
  states: Option[],
  metros?: Option[],
  selectedState?: Option | null,
  selectedMetros?: Option[]
}

interface FilterStateAction
{
  type: FilterStateActionKind,
  payload?: any
}

enum FilterStateActionKind
{
  CHANGE_STATE,
  CHANGE_METRO,
  RESET
}

const getMetroOptions = (stateId?: number) : Option[] => {
  if (!stateId?.toString) {
    return []
  }

  return allMetros[stateId];  
}

const initialState: FilterState = {
  states,
  metros: getMetroOptions(states[0].value),
  selectedState: states[0],
  selectedMetros: []
}

const reducer = (state: FilterState, action: FilterStateAction): FilterState => {
  console.log(action.type)
  switch (action.type) {
    case FilterStateActionKind.CHANGE_STATE:
      const nextState = { ...state, selectedState: action.payload, selectedMetros: [] }

      nextState.metros = getMetroOptions(nextState.selectedState?.value);

      return nextState;
    case FilterStateActionKind.CHANGE_METRO:
      return { ...state, selectedMetros: action.payload };
    case FilterStateActionKind.RESET:
      return { ...state, selectedState: null, selectedMetros: [] }
    default:
      return state;
  }
};

export default function Home() {
  const [state, dispatch] = useReducer(reducer, initialState)
 
  const onStateSelectChanged = useCallback(
    (newValue: unknown, _actionMeta: ActionMeta<unknown>): void =>
      dispatch({ type: FilterStateActionKind.CHANGE_STATE, payload: newValue })
    , []
  );

  const onMetroSelectChanged = useCallback(
    (newValue: unknown, _actionMeta: ActionMeta<unknown>): void =>
      dispatch({ type: FilterStateActionKind.CHANGE_METRO, payload: newValue })
    , []
  );

  const onResetButtonClicked = useCallback(
    (e: React.MouseEvent<HTMLButtonElement>): void => {
      dispatch({ type: FilterStateActionKind.RESET })
    }, []
  )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StateSelect options={states} onChange={onStateSelectChanged} value={state.selectedState} />
        <MetroSelect options={state.metros} isMulti onChange={onMetroSelectChanged} value={state.selectedMetros} />
        <button onClick={onResetButtonClicked}>Reset</button>
      </main>
    </>
  )
}
